apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels: 
    app: backend-app      
    
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000

